version: '3.9'
services:
  backend_auth:
    build:
      context: .
      dockerfile: Dockerfile
    # command: bash -c "python manage.py makemigrations && python manage.py migrate"
    ports:
      - 8000:8000
    env_file:
      - .env
 